name: Build Docker toolchain

on:
  - workflow_dispatch

jobs:
  publish_docker_image:
    name: Build Docker toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: .
          fetch-depth: 0

      - name: Build Docker image
        run: |
          docker build -t "rrdash/tomb3main:latest" . -f docker/Dockerfile
          docker push "rrdash/tomb3main:latest"
